version: '3.9'

services:
  backend:
    build: ./backend
    expose:
      - "5000"
    networks:
      - appnet

  frontend:
    build: ./frontend
    expose:
      - "80"
    networks:
      - appnet

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - appnet

networks:
  appnet:
