version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - appnet

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    networks:
      - appnet

networks:
  appnet:
